import { ll } from "./localLib.js"

export const marketItemList = {
    "tables": {
        categoryName: "Столы",
        categoryClassName: "tables",
        elementId: "table-section",
        secondaryClassName: ".table-nav",
        itemsList: [
            {
            name: "Стол Ассен",
            isNew: false,
            isSale: true,
            salePercent: 12,
            size: "120x80",
            url: "./image/content/tables/assen/assen1.jpg",
            urlOne: "./image/content/tables/assen/assen2.jpg",
            imgAltName: "table-assen",
            material: "Массив Ясеня", 
            type: "Обеденный",
            width: "120",
            height: "76",
            depth: "80",
            weight: "35",
            country: "Украина",
            paragraph: "Самый популярный стол для дома в современном дизайне из массива натурального ясеня. Подойдет для кухни, столовой, или как письменный стол. Изготовлен из натурального дерева и покрыт масло-воском на основе натуральных органических компонентов, что позволяет подчеркнуть фактуру ясеня и оставляет ощущение открытого дерева.",
            price: "5336",
            cartAmount: 1,
            id: "table-assen-120x80"
        }, {
            name: "Стол Кембридж",
            isNew: false,
            isSale: true,
            salePercent: 7,
            size: "128x70",
            url: "./image/content/tables/cambridge/cambridge1.jpg",
            urlOne: "./image/content/tables/cambridge/cambridge2.jpg",
            imgAltName: "table-cambridge",
            material: "Массив Ясеня", 
            type: "Письменный",
            width: "128",
            height: "76",
            depth: "70",
            weight: "46",
            country: "Украина",
            paragraph: "Стильный и удобный письменный стол. Комбинация металлических опор со столешницей из натурального дерева.",
            price: "9310",
            cartAmount: 1,
            id: "table-cambridge-128x70"
        }, {
            name: "Стол Лутон",
            isNew: true,
            isSale: false,
            size: "120x60",
            url: "./image/content/tables/luton/luton1.jpg",
            urlOne: "./image/content/tables/luton/luton2.jpg",
            imgAltName: "table-luton",
            material: "Массив Ясеня", 
            type: "Письменный",
            width: "120",
            height: "75",
            depth: "60",
            weight: "39",
            country: "Украина",
            paragraph: "Новий сучасний письмовий стіл із натурального ясену.",
            price: "7990",
            cartAmount: 1,
            id: "table-luton-120x60"
        }, {
            name: "Стол Чикаго",
            isNew: false,
            isSale: false,
            size: "180x90",
            url: "./image/content/tables/chicago/chicago1.jpg",
            urlOne: "./image/content/tables/chicago/chicago2.jpg",
            imgAltName: "table-chicago",
            material: "Массив Ясеня", 
            type: "Письменный",
            width: "180",
            height: "76",
            depth: "90",
            weight: "69",
            country: "Украина",
            paragraph: "Надежный обеденный стол из массива натурального ясеня. Опоры из грубого металла формируют трапециевидный силуэт.",
            price: "10650",
            cartAmount: 1,
            id: "table-chicago-180x90"
        }, {
            name: "Стол Оксфорд",
            isNew: false,
            isSale: false,
            size: "120x80",
            url: "./image/content/tables/oxford/oxford1.jpg",
            urlOne: "./image/content/tables/oxford/oxford2.jpg",
            imgAltName: "table-oxford",
            material: "Массив Ясеня", 
            type: "Письменный",
            width: "120",
            height: "76",
            depth: "80",
            weight: "35",
            country: "Украина",
            paragraph: "Стол из натурального дерева. Отличается лаконичностью и функциональностью. Подойдет для офиса или дома.",
            price: "6410",
            cartAmount: 1,
            id: "table-oxford-120x80"
        }, {
            name: "Стол Йотса",
            isNew: true,
            isSale: true,
            salePercent: 3,
            size: "120x65",
            url: "./image/content/tables/yotsa/yotsa1.jpg",
            urlOne: "./image/content/tables/yotsa/yotsa2.jpg",
            imgAltName: "table-yotsa",
            material: "Массив Ясеня", 
            type: "Письменный",
            width: "120",
            height: "76",
            depth: "65",
            weight: "40",
            country: "Украина",
            paragraph: "Натуральное дерево. Скандинавский дизайн. Чудесная функциональность и непревзойденная надежность. Настоящий уют вашего рабочего пространства получите с письменный столом Йотса.",
            price: "8556",
            cartAmount: 1,
            id: "table-yotsa-120x65"
        }],
    },
    "beds": {
        categoryName: "Кровати",
        categoryClassName: "beds",
        elementId: "bed-section",
        secondaryClassName: ".bed-nav",
        itemsList: [{
            name: "Кровать Берген",
            isNew: false,
            isSale: false,
            size: "200x200",
            url: "./image/content/beds/bergen/bergen1.jpg",
            urlOne: "./image/content/beds/bergen/bergen1.jpg",
            material: "Массив Ясеня", 
            type: "Для Спальни",
            width: "206",
            height: "87",
            depth: "206",
            weight: "76",
            country: "Украина",
            paragraph: "Главный элемент спальни - современная комфортная кровать. Материал - массив ясеня, каркас из окрашенного металла. Покрытие масло-воск позволяет оставить текстуру дерева неизменной, приятной на ощупь. Матрас не входит в стоимость.",
            imgAltName: "bed-bergen",
            price: "17710",
            cartAmount: 1,
            id: "bed-bergen-200x200"
        }, {
            name: "Кровать Блум",
            isNew: false,
            isSale: false,
            size: "160x200",
            url: "./image/content/beds/blum/blum1.jpg",
            urlOne: "./image/content/beds/blum/blum2.jpg",
            imgAltName: "bed-blum",
            material: "Массив Ясеня", 
            type: "Для Спальни",
            width: "186",
            height: "96",
            depth: "222",
            weight: "90",
            country: "Украина",
            paragraph: "Кровать из новой коллекции Блум. Качество и надежность в легких очертаниях. Тонкие металлические опоры и натуральное дерево для создания современной комфортной спальни. Матрас в стоимость не входит, его можно приобрести отдельно.",
            price: "18180",
            cartAmount: 1,
            id: "bed-blum-160x200"
        }, {
            name: "Кровать Мальме",
            isNew: true,
            isSale: false,
            size: "180x200",
            url: "./image/content/beds/malme/malme1.jpg",
            urlOne: "./image/content/beds/malme/malme2.jpg",
            imgAltName: "bed-malme",
            material: "Массив Ясеня", 
            type: "Письменный",
            width: "189",
            height: "88",
            depth: "217",
            weight: "100",
            country: "Украина",
            paragraph: "Идеальная кровать с подъемным механизмом изготовлена из массива ясеня.",
            price: "20180",
            cartAmount: 1,
            id: "bed-malme-180x200"
        }, {
            name: "Кровать Норидж",
            isNew: true,
            isSale: true,
            salePercent: 6,
            size: "180x200",
            url: "./image/content/beds/noridge/noridge1.jpg",
            urlOne: "./image/content/beds/noridge/noridge2.jpg",
            imgAltName: "bed-noridge",
            material: "Массив Ясеня", 
            type: "Письменный",
            width: "198",
            height: "92",
            depth: "212",
            weight: "110",
            country: "Украина",
            paragraph: "Простая форма, натуральное дерево, близость к природе - это привычно, поэтому супер комфортно. Кровать Норидж сочетает хрупкий дизайн и прочную несущую конструкцию.",
            price: "11600",
            cartAmount: 1,
            id: "bed-noridge-180x200"
        }, {
            name: "Кровать Оксфорд",
            isNew: false,
            isSale: true,
            salePercent: 10,
            size: "160x200",
            url: "./image/content/beds/oxford/oxford1.jpg",
            urlOne: "./image/content/beds/oxford/oxford2.jpg",
            imgAltName: "table-oxford",
            material: "Массив Ясеня", 
            type: "Письменный",
            width: "166",
            height: "86",
            depth: "212",
            weight: "70",
            country: "Украина",
            paragraph: "Главный элемент спальни - современная комфортная кровать. Материал - массив ясеня, каркас из окрашенного металла. Покрытие масло-воск позволяет оставить текстуру дерева неизменной, приятной на ощупь. Матрас не входит в стоимость.",
            price: "14100",
            cartAmount: 1,
            id: "bed-oxford-160x200"
        }],
    },
    "racks": {
        categoryName: "Стеллажи",
        categoryClassName: "racks",
        elementId: "rack-section",
        secondaryClassName: ".rack-nav",
        itemsList: [{
            name: "Стеллаж Брикс",
            isNew: true,
            isSale: false,
            size: "68x35",
            url: "./image/content/racks/bricks/bricks1.jpg",
            urlOne: "./image/content/racks/bricks/bricks2.jpg",
            material: "Массив Ясеня", 
            type: "Стеллаж",
            width: "68",
            height: "143",
            depth: "35",
            weight: "76",
            country: "Украина",
            paragraph: "Тонкие металлические опоры и полки, интересный асимметричный дизайн, компактные размеры. Этот стеллаж - находка для небольших пространств. Книги, вазоны или декор будут выглядеть одинаково уместно и красиво. Дерево ясень, покрытие - масло-воск. Металлические опоры могут быть белыми, черными, или же покрытыми прозрачным лаком.",
            imgAltName: "rack-bricks",
            price: "9700",
            cartAmount: 1,
            id: "rack-bricks-68x35"
        }, {
            name: "Консоль Брикс",
            isNew: false,
            isSale: true,
            salePercent: 14,
            size: "100x35",
            url: "./image/content/racks/bricksCoridor/bricks1.jpg",
            urlOne: "./image/content/racks/bricksCoridor/bricks2.jpg",
            imgAltName: "rack-bricks",
            material: "Массив Ясеня", 
            type: "Стеллаж",
            width: "100",
            height: "35",
            depth: "47",
            weight: "50",
            country: "Украина",
            paragraph: "Эта консоль - находка для небольших пространств.  Дерево ясень, покрытие - масло-воск. Металлические опоры могут быть белыми, черными, или же покрытыми прозрачным лаком.",
            price: "5990",
            cartAmount: 1,
            id: "rack-bricks-100x35"
        }, {
            name: "Стеллаж Кембридж",
            isNew: false,
            isSale: false,
            size: "61x40",
            url: "./image/content/racks/cambridge/cambridge1.jpg",
            urlOne: "./image/content/racks/cambridge/cambridge2.jpg",
            imgAltName: "rack-cambridge",
            material: "Массив Ясеня", 
            type: "Стеллаж",
            width: "61",
            height: "200",
            depth: "40",
            weight: "56",
            country: "Украина",
            paragraph: "Современный универсальный стеллаж для дома или офиса. Полки из массива натурального ясеня толщиной 30мм. Конструкция металлических опор из уголка 40х40мм черного цвета.",
            price: "9960",
            cartAmount: 1,
            id: "rack-cambridge-61x40"
        }, {
            name: "Стеллаж Лагом",
            isNew: true,
            isSale: true,
            salePercent: 12,
            size: "80x34",
            url: "./image/content/racks/lagom/lagom1.jpg",
            urlOne: "./image/content/racks/lagom/lagom2.jpg",
            imgAltName: "rack-lagom",
            material: "Массив Ясеня", 
            type: "Стеллаж",
            width: "80",
            height: "180",
            depth: "34",
            weight: "110",
            country: "Украина",
            paragraph: "Простая форма, натуральное дерево, близость к природе - это привычно, поэтому супер комфортно. Кровать Норидж сочетает хрупкий дизайн и прочную несущую конструкцию.",
            price: "6500",
            cartAmount: 1,
            id: "rack-lagom-80x34"
        }]
    },
    "chairs": {
        categoryName: "Стулья",
        categoryClassName: "chairs",
        elementId: "chair-section",
        secondaryClassName: ".chair-nav",
        itemsList: [{
            name: "Скамья Ассен",
            isNew: false,
            isSale: false,
            size: "160x40",
            url: "./image/content/chairs/assen/assen1.jpg",
            urlOne: "./image/content/chairs/assen/assen2.jpg",
            material: "Массив Ясеня", 
            type: "Скамья",
            width: "160",
            height: "45",
            depth: "40",
            weight: "20",
            country: "Украина",
            paragraph: "Простая в исполнении и практичная в использовании скамья Ассен может стать отличным дополнением к обеденному столу из этой коллекции или любого другого по вашему желанию. Натуральный ясень, массив покрытый маслом с твердым воском. Надежная и удобная штука для любого дома!",
            imgAltName: "chair-assen",
            price: "5250",
            cartAmount: 1,
            id: "chair-assen-160x40"
        }, {
            name: "Табурет Гесби",
            isNew: true,
            isSale: false,
            size: "100x35",
            url: "./image/content/chairs/gesbi/gesbi1.jpg",
            urlOne: "./image/content/chairs/gesbi/gesbi2.jpg",
            imgAltName: "chair-gesby",
            material: "Массив Ясеня", 
            type: "Табурет",
            width: "39",
            height: "29",
            depth: "25",
            weight: "1",
            country: "Украина",
            paragraph: "Табурет Гэтсби стал еще легче и намного ярче. Компактный, супер-устойчивый, незаменимый дома.",
            price: "990",
            cartAmount: 1,
            id: "chair-gesby-100x35"
        }, {
            name: "Скамья Рустик",
            isNew: false,
            isSale: false,
            size: "180x200",
            url: "./image/content/chairs/rustik/rustik1.jpg",
            urlOne: "./image/content/chairs/rustik/rustik2.jpg",
            imgAltName: "chair-rustik",
            material: "Массив Ясеня", 
            type: "Скамья",
            width: "160",
            height: "48",
            depth: "34",
            weight: "15",
            country: "Украина",
            paragraph: "Современный универсальный стеллаж для дома или офиса. Полки из массива натурального ясеня толщиной 30мм. Конструкция металлических опор из уголка 40х40мм черного цвета.Скамья в стиле кантри. Популярный европейский дизайн для дома или офиса. Самое универсальное применение от прихожей до кухни.",
            price: "6077",
            cartAmount: 1,
            id: "chair-rustik-61x40"
        }, {
            name: "Табурет Ливерпуль",
            isNew: true,
            isSale: true,
            salePercent: 23,
            size: "180x200",
            url: "./image/content/chairs/liverpool/liverpool1.jpg",
            urlOne: "./image/content/chairs/liverpool/liverpool2.jpg",
            imgAltName: "chair-liver",
            material: "Массив Ясеня", 
            type: "Стеллаж",
            width: "40",
            height: "45",
            depth: "40",
            weight: "2",
            country: "Украина",
            paragraph: "Легкая металлическая опора и сидение из массива ясеня дают устойчивый и одновременно удобный в перестановке табурет. Войлочные накладки внизу каркаса защищают пол от царапин. По умолчанию опора покрывается прозрачным лаком, но под заказ может быть выкрашена в черный или белый цвет. Покрытие опоры на цену не влияет.",
            price: "2410",
            cartAmount: 1,
            id: "chair-liver"
        }]
    },
}

export const catNameList = ["tables", "beds", "racks", "chairs"] 

catNameList.forEach(item => {
    ll.createMarketCategory(marketItemList[item]);
});
